#cloudbuild.yaml

steps:
#- name: 'docker/compose:1.25.1'
#  args: ['up', '-d']

# Build the new docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
  
# Push the new image to the registry.
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
