#cloudbuild.yaml

steps:
#- name: 'docker/compose:1.25.1'
#  args: ['up', '-d']

## Build the new docker image.
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
#
## Push the new image to the registry.
#images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  - name: python:3.10
    id: "python_install_config_test"
    args:
      - "sh"
      - "-c"
      - |
        python.exe -m pip install --upgrade pip \
        && pip3 install -r requirements.txt \
        && pytest test -s --cov=. --cov-fail-under 100 --log-cli-level info
    env:
      - "PROJECT_ID=$PROJECT_ID"

  - id: "docker_build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.'"]

  - id: "docker_push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.'"]

  - id: "cloud_run_deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "$REPO_NAME-$BRANCH_NAME",
        "--image=gcr.io/$PROJECT_ID/$REPO_NAME:latest",
        "--cpu=2",
        "--port=8080",
        "--memory=2048Mi",
        "--timeout=600",
        "--concurrency=20",
        "--platform=managed",
        "--max-instances=1000",
        "--region=europe-west1",
        "--allow-unauthenticated",
        "--revision-suffix=$SHORT_SHA",
        "--set-env-vars=PROJECT_ID=$PROJECT_ID,SHORT_SHA=$SHORT_SHA",
        "--set-cloudsql-instances=$PROJECT_ID:europe-west1:runfastapi",
        "--service-account=298558544785-compute@developer.gserviceaccount.com",
      ]